name: Comment on PR
description: Adds a comment on the current PR

inputs:
  MESSAGE:
    description: The message to display
    required: true
  ONLY_POST_ONCE:
    description: Check whether the current message has already been posted before posting again
    default: false
    required: false
  UNIQUE_KEY:
    description: A unique key attached invisibly to the comment, for use with the ONLY_POST_ONCE option
    default: gh-actions--comment-on-pr
    required: false

runs:
  using: composite
  steps:
    - name: Find Previous Comment
      if: ${{ inputs.ONLY_POST_ONCE != 'false' }}
      uses: Brightspace/third-party-actions@peter-evans/find-comment
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: ${{ inputs.UNIQUE_KEY }}

    - name: PR Deployment URLs
      if: ${{ inputs.ONLY_POST_ONCE == 'false' || steps.fc.outputs.comment-id == '' }}
      uses: Brightspace/third-party-actions@actions/github-script
      env:
        MESSAGE: ${{ inputs.MESSAGE }}
        UNIQUE_KEY: ${{ inputs.UNIQUE_KEY }}
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `<!-- ${process.env.UNIQUE_KEY} -->\n\n${process.env.MESSAGE}`
          })
