name: License Checker
on: pull_request
jobs:
  lint:
    name: License Checker
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          npm install d2l-license-checker@4 --no-save
      - name: Check License
        run: npx d2l-license-checker -p
