name: License Checker
on: pull_request
jobs:
  lint:
    name: License Checker
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'
      - uses: Brightspace/third-party-actions@actions/cache
        id: cache
        with:
          path: '**/node_modules'
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Check License
        run: |
          npm install d2l-license-checker@4 --no-save
          npx d2l-license-checker -p
